// imageMapping.js

export const monstersImages = {
    "QualityBone.png": require("../assets/components/WhiteBone.webp"),
    "Rathalos.png": require("../assets/monsters/Rathalos.webp"),
    "GreatJagras.png": require("../assets/monsters/GreatJagras.webp"),
    "Anjanath.png": require("../assets/monsters/Anjanath.webp"),
    "Barroth.png": require("../assets/monsters/Barroth.webp"),
    "Diablos.png": require("../assets/monsters/Diablos.webp"),
    "Jyuratodus.png": require("../assets/monsters/Jyuratodus.webp"),
    "KuluYaKu.png": require("../assets/monsters/KuluYaKu.webp"),
    "BlackDiablos.png": require("../assets/monsters/BlackDiablos.webp"),
    "TobiKadachi.png": require("../assets/monsters/TobiKadachi.webp"),
    "Nergigante.png": require("../assets/monsters/Nergigante.webp"),
    "KushalaDaora.png": require("../assets/monsters/KushalaDaora.webp"),
    "Teostra.png": require("../assets/monsters/Teostra.webp"),
    "PukeiPukei.png": require("../assets/monsters/PukeiPukei.webp"),
    "AzureRathalos.png": require("../assets/monsters/AzureRathalos.webp"),
    "Ores.png": require("../assets/components/WhiteOre.webp"),
    "Bones.png": require("../assets/components/YellowBone.webp"),
    "Minerals.png": require("../assets/components/WhiteMinerals.webp"),
    "Pelts.png": require("../assets/components/WhitePelt.webp"),
  };
  
  export const componentsImages = {
    "QualityBone.png": require('../assets/components/WhiteBone.webp'),
    "CarbaliteOre.png": require("../assets/components/PurpleOre.webp"),
    "MachaliteOre.png": require("../assets/components/FadedBlueOre.webp"),
    "DragoniteOre.png": require("../assets/components/TealOre.webp"),
    "FuciumOre.png": require("../assets/components/FadedPinkOre.webp"),
    "DragonveinCrystal.png": require("../assets/components/DarkOrangeOre.webp"),
    "MonsterBoneSmall.png": require("../assets/components/YellowBone.webp"),
    "MonsterBoneMedium.png": require("../assets/components/YellowBone.webp"),
    "MonsterBoneLarge.png": require("../assets/components/YellowBone.webp"),
    "AncientBone.png": require("../assets/components/FadedGreenBone.webp"),
    "MonsterKeenbone.png": require("../assets/components/FadedPinkBone.webp"),
    "MonsterHardbone.png": require("../assets/components/DarkRedBone.webp"),
    "BoulderBone.png": require("../assets/components/YellowBone.webp"),
    "WingdrakeHide.png": require("../assets/components/WhiteWing.webp"),

    "AquaSac.png": require("../assets/components/FadedBlueSac.webp"),
    "BirdWyvernGem.png": require("../assets/components/FadedGreenGem.webp"),
    "BlackSpiralHorn.png": require("../assets/components/BlackBone.webp"),
    "BlosMedulla.png": require("../assets/components/DarkOrangeBone.webp"),
    "CoralCrystal.png": require("../assets/components/TealOre.webp"),
    "EarthCrystal.png": require("../assets/components/WhiteOre.webp"),
    "ElderDragonBlood.png": require("../assets/components/DarkRedPotion.webp"), //
    "ElderDragonBone.png": require("../assets/components/VioletBone.webp"),
    "Electrode.png": require("../assets/components/FadedBlueBone.webp"),
    "ElectroSac.png": require("../assets/components/YellowSac.webp"),
    "FertileMud.png": require("../assets/components/FadedOrangeMud.webp"),
    "FirecellStone.png": require("../assets/components/DarkOrangeOre.webp"),
    "FireDragonScale.png": require("../assets/components/DarkRedScale.webp"),
    "FlameSac.png": require("../assets/components/DarkRedSac.webp"),
    "GajauScale.png": require("../assets/components/YellowPelt.webp"),
    "ImmortalDragonscale.png": require("../assets/components/GreyScale.webp"),
    "InfernoSac.png": require("../assets/components/DarkRedSac.webp"), //
    "MajesticHorn.png": require("../assets/components/DarkOrangeClaw.webp"),
    "Novacrystal.png": require("../assets/components/WhiteOre.webp"),
    "PiercingClaw.png": require("../assets/components/GreyClaw.webp"),
    "PoisonSac.png": require("../assets/components/VioletSac.webp"),
    "SharpClaw.png": require("../assets/components/WhiteClaw.webp"),
    "ThunderSac.png": require("../assets/components/YellowSac.webp"),
    "ToxinSac.png": require("../assets/components/FadedGreenSac.webp"),
    "TwistedHorn.png": require("../assets/components/FadedPinkClaw.webp"),
    "WarmPelt.png": require("../assets/components/FadedGreenPelt.webp"),
    "WyvernGem.png": require("../assets/components/FadedBlueGem.webp"),

    "GreatJagrasClaw.png": require("../assets/components/YellowClaw.webp"),
    "GreatJagrasHide.png": require("../assets/components/YellowPelt.webp"),
    "GreatJagrasMane.png": require("../assets/components/YellowPart.webp"),
    "GreatJagrasScale.png": require("../assets/components/YellowScale.webp"),

    "BarrothCarapace.png": require("../assets/components/DarkOrangeShell.webp"),
    "BarrothClaw.png": require("../assets/components/DarkOrangeClaw.webp"),
    "BarrothRidge.png": require("../assets/components/DarkOrangePart.webp"),
    "BarrothShell.png": require("../assets/components/DarkOrangeShell.webp"),

    "TobiKadachiClaw.png": require("../assets/components/BlueClaw.webp"),
    "TobiKadachiElectrode.png": require("../assets/components/BluePart.webp"),
    "TobiKadachiMembrane.png": require("../assets/components/BlueWing.webp"),
    "TobiKadachiPelt.png": require("../assets/components/BluePelt.webp"),
    "TobiKadachiScale.png": require("../assets/components/BlueScale.webp"),

    "BlackDiablosCarapace.png": require("../assets/components/BlackShell.webp"),
    "BlackDiablosRidge.png": require("../assets/components/BlackPart.webp"),

    "KuluYaKuBeak.png": require("../assets/components/DarkYellowHead.webp"),
    "KuluYaKuHide.png": require("../assets/components/DarkYellowPelt.webp"),
    "KuluYaKuPlume.png": require("../assets/components/DarkYellowPart.webp"),
    "KuluYaKuScale.png": require("../assets/components/DarkYellowScale.webp"),

    "JyuratodusCarapace.png": require("../assets/components/DarkYellowHead.webp"),
    "JyuratodusFang.png": require("../assets/components/DarkYellowPelt.webp"),
    "JyuratodusFin.png": require("../assets/components/DarkYellowPart.webp"),
    "JyuratodusScale.png": require("../assets/components/DarkYellowScale.webp"),
    "JyuratodusShell.png": require("../assets/components/LightOrangeShell.webp"),

    "PukeiPukeiCarapace.png": require("../assets/components/LightTealShell.webp"),
    "PukeiPukeiQuill.png": require("../assets/components/LightTealWing.webp"),
    "PukeiPukeiSac.png": require("../assets/components/LightTealSac.webp"),
    "PukeiPukeiScale.png": require("../assets/components/LightTealScale.webp"),
    "PukeiPukeiTail.png": require("../assets/components/LightTealTail.webp"),
    "PukeiPukeiWing.png": require("../assets/components/LightTealWing.webp"),

    "AnjanathFang.png": require("../assets/components/FadedPinkClaw.webp"),
    "AnjanathNoseBone.png": require("../assets/components/FadedPinkBone.webp"),
    "AnjanathPelt.png": require("../assets/components/FadedPinkPelt.webp"),
    "AnjanathScale.png": require("../assets/components/FadedPinkScale.webp"),
    "AnjanathTail.png": require("../assets/components/FadedPinkTail.webp"),

    "DiablosCarapace.png": require("../assets/components/LightOrangeShell.webp"),
    "DiablosFang.png": require("../assets/components/LightOrangeClaw.webp"),
    "DiablosRidge.png": require("../assets/components/LightOrangePart.webp"),
    "DiablosShell.png": require("../assets/components/LightOrangeShell.webp"),

    "DaoraCarapace.png": require("../assets/components/FadedPurpleShell.webp"),
    "DaoraClaw.png": require("../assets/components/FadedPurpleClaw.webp"),
    "DaoraDragonScale.png": require("../assets/components/FadedPurpleScale.webp"),
    "DaoraDragonGem.png": require("../assets/components/FadedPurpleGem.webp"),
    "DaoraDragonHorn.png": require("../assets/components/FadedPurpleClaw.webp"),
    "DaoraDragonTail.png": require("../assets/components/FadedPurpleTail.webp"),
    "DaoraDragonWebbing.png": require("../assets/components/FadedPurpleWebbing.webp"),

    "TeostraCarapace.png": require("../assets/components/FadedPinkShell.webp"),
    "TeostraClaw.png": require("../assets/components/FadedPinkClaw.webp"),
    "TeostraGem.png": require("../assets/components/FadedPinkGem.webp"),
    "TeostraHorn.png": require("../assets/components/FadedPinkClaw.webp"),
    "TeostraMane.png": require("../assets/components/FadedPinkPart.webp"),
    "TeostraPowder.png": require("../assets/components/FadedPinkSac.webp"),

  };

  export const equipementsImages = {
    "ChestRarity1.png": require("../assets/armor/ChestRarity1.webp"),
    "LegRarity1.png": require("../assets/armor/LegRarity1.webp"),
    "HelmetRarity1.png": require("../assets/armor/HelmetRarity1.webp"),

    "ChestRarity2.png": require("../assets/armor/ChestRarity2.webp"),
    "LegRarity2.png": require("../assets/armor/LegRarity2.webp"),
    "HelmetRarity2.png": require("../assets/armor/HelmetRarity2.webp"),

    "ChestRarity3.png": require("../assets/armor/ChestRarity3.webp"),
    "LegRarity3.png": require("../assets/armor/LegRarity3.webp"),
    "HelmetRarity3.png": require("../assets/armor/HelmetRarity3.webp"),

    "ChestRarity4.png": require("../assets/armor/ChestRarity4.webp"),
    "LegRarity4.png": require("../assets/armor/LegRarity4.webp"),
    "HelmetRarity4.png": require("../assets/armor/HelmetRarity4.webp"),

    "ChestRarity5.png": require("../assets/armor/ChestRarity5.webp"),
    "LegRarity5.png": require("../assets/armor/LegRarity5.webp"),
    "HelmetRarity5.png": require("../assets/armor/HelmetRarity5.webp"),

    "GreatSwordRarity1.png": require("../assets/weapons/greatSword/GreatSwordRarity1.webp"),
    "GreatSwordRarity2.png": require("../assets/weapons/greatSword/GreatSwordRarity2.webp"),
    "GreatSwordRarity3.png": require("../assets/weapons/greatSword/GreatSwordRarity3.webp"),
    "GreatSwordRarity4.png": require("../assets/weapons/greatSword/GreatSwordRarity4.webp"),
    "GreatSwordRarity5.png": require("../assets/weapons/greatSword/GreatSwordRarity5.webp"),

    "LongSwordRarity1.png": require("../assets/weapons/longSword/LongSwordRarity1.webp"),
    "LongSwordRarity2.png": require("../assets/weapons/longSword/LongSwordRarity2.webp"),
    "LongSwordRarity3.png": require("../assets/weapons/longSword/LongSwordRarity3.webp"),
    "LongSwordRarity4.png": require("../assets/weapons/longSword/LongSwordRarity4.webp"),
    "LongSwordRarity5.png": require("../assets/weapons/longSword/LongSwordRarity5.webp"),

    "HammerRarity1.png": require("../assets/weapons/hammer/HammerRarity1.webp"),
    "HammerRarity2.png": require("../assets/weapons/hammer/HammerRarity2.webp"),
    "HammerRarity3.png": require("../assets/weapons/hammer/HammerRarity3.webp"),
    "HammerRarity4.png": require("../assets/weapons/hammer/HammerRarity4.webp"),
    "HammerRarity5.png": require("../assets/weapons/hammer/HammerRarity5.webp"),

    "ChargeBladeRarity1.png": require("../assets/weapons/chargeBlade/ChargeBladeRarity1.webp"),
    "ChargeBladeRarity2.png": require("../assets/weapons/chargeBlade/ChargeBladeRarity2.webp"),
    "ChargeBladeRarity3.png": require("../assets/weapons/chargeBlade/ChargeBladeRarity3.webp"),
    "ChargeBladeRarity4.png": require("../assets/weapons/chargeBlade/ChargeBladeRarity4.webp"),
    "ChargeBladeRarity5.png": require("../assets/weapons/chargeBlade/ChargeBladeRarity5.webp"),

    "InsectGlaiveRarity1.png": require("../assets/weapons/insectGlaive/InsectGlaiveRarity1.webp"),
    "InsectGlaiveRarity2.png": require("../assets/weapons/insectGlaive/InsectGlaiveRarity2.webp"),
    "InsectGlaiveRarity3.png": require("../assets/weapons/insectGlaive/InsectGlaiveRarity3.webp"),
    "InsectGlaiveRarity4.png": require("../assets/weapons/insectGlaive/InsectGlaiveRarity4.webp"),
    "InsectGlaiveRarity5.png": require("../assets/weapons/insectGlaive/InsectGlaiveRarity5.webp"),

    "HuntingHornRarity1.png": require("../assets/weapons/huntingHorn/HuntingHornRarity1.webp"),
    "HuntingHornRarity2.png": require("../assets/weapons/huntingHorn/HuntingHornRarity2.webp"),
    "HuntingHornRarity3.png": require("../assets/weapons/huntingHorn/HuntingHornRarity3.webp"),
    "HuntingHornRarity4.png": require("../assets/weapons/huntingHorn/HuntingHornRarity4.webp"),
    "HuntingHornRarity5.png": require("../assets/weapons/huntingHorn/HuntingHornRarity5.webp"),

    "BowRarity1.png": require("../assets/weapons/bow/BowRarity1.webp"),
    "BowRarity2.png": require("../assets/weapons/bow/BowRarity2.webp"),
    "BowRarity3.png": require("../assets/weapons/bow/BowRarity3.webp"),
    "BowRarity4.png": require("../assets/weapons/bow/BowRarity4.webp"),
    "BowRarity5.png": require("../assets/weapons/bow/BowRarity5.webp"),

    "DualBladesRarity1.png": require("../assets/weapons/dualBlades/DualBladesRarity1.webp"),
    "DualBladesRarity2.png": require("../assets/weapons/dualBlades/DualBladesRarity2.webp"),
    "DualBladesRarity3.png": require("../assets/weapons/dualBlades/DualBladesRarity3.webp"),
    "DualBladesRarity4.png": require("../assets/weapons/dualBlades/DualBladesRarity4.webp"),
    "DualBladesRarity5.png": require("../assets/weapons/dualBlades/DualBladesRarity5.webp"),

    "SwitchAxeRarity1.png": require("../assets/weapons/switchAxe/SwitchAxeRarity1.webp"),
    "SwitchAxeRarity2.png": require("../assets/weapons/switchAxe/SwitchAxeRarity2.webp"),
    "SwitchAxeRarity3.png": require("../assets/weapons/switchAxe/SwitchAxeRarity3.webp"),
    "SwitchAxeRarity4.png": require("../assets/weapons/switchAxe/SwitchAxeRarity4.webp"),
    "SwitchAxeRarity5.png": require("../assets/weapons/switchAxe/SwitchAxeRarity5.webp"),

    "HeavyBowgunRarity1.png": require("../assets/weapons/heavyBowgun/HeavyBowgunRarity1.webp"),
    "HeavyBowgunRarity2.png": require("../assets/weapons/heavyBowgun/HeavyBowgunRarity2.webp"),
    "HeavyBowgunRarity3.png": require("../assets/weapons/heavyBowgun/HeavyBowgunRarity3.webp"),
    "HeavyBowgunRarity4.png": require("../assets/weapons/heavyBowgun/HeavyBowgunRarity4.webp"),
    "HeavyBowgunRarity5.png": require("../assets/weapons/heavyBowgun/HeavyBowgunRarity5.webp"),

    "LightBowgunRarity1.png": require("../assets/weapons/lightBowgun/LightBowgunRarity1.webp"),
    "LightBowgunRarity2.png": require("../assets/weapons/lightBowgun/LightBowgunRarity2.webp"),
    "LightBowgunRarity3.png": require("../assets/weapons/lightBowgun/LightBowgunRarity3.webp"),
    "LightBowgunRarity4.png": require("../assets/weapons/lightBowgun/LightBowgunRarity4.webp"),
    "LightBowgunRarity5.png": require("../assets/weapons/lightBowgun/LightBowgunRarity5.webp"),

    "SwordAndShieldRarity1.png": require("../assets/weapons/swordAndShield/SwordAndShieldRarity1.webp"),
    "SwordAndShieldRarity2.png": require("../assets/weapons/swordAndShield/SwordAndShieldRarity2.webp"),
    "SwordAndShieldRarity3.png": require("../assets/weapons/swordAndShield/SwordAndShieldRarity3.webp"),
    "SwordAndShieldRarity4.png": require("../assets/weapons/swordAndShield/SwordAndShieldRarity4.webp"),
    "SwordAndShieldRarity5.png": require("../assets/weapons/swordAndShield/SwordAndShieldRarity5.webp"),

    "LanceRarity1.png": require("../assets/weapons/lance/LanceRarity1.webp"),
    "LanceRarity2.png": require("../assets/weapons/lance/LanceRarity2.webp"),
    "LanceRarity3.png": require("../assets/weapons/lance/LanceRarity3.webp"),
    "LanceRarity4.png": require("../assets/weapons/lance/LanceRarity4.webp"),
    "LanceRarity5.png": require("../assets/weapons/lance/LanceRarity5.webp"),

    "GunlanceRarity1.png": require("../assets/weapons/gunlance/GunlanceRarity1.webp"),
    "GunlanceRarity2.png": require("../assets/weapons/gunlance/GunlanceRarity2.webp"),
    "GunlanceRarity3.png": require("../assets/weapons/gunlance/GunlanceRarity3.webp"),
    "GunlanceRarity4.png": require("../assets/weapons/gunlance/GunlanceRarity4.webp"),
    "GunlanceRarity5.png": require("../assets/weapons/gunlance/GunlanceRarity5.webp"),

  };